@startuml manage-campground

header Campground Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Campground (Update Campground)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<routes>>\n:campgrounds" as routerCampgrounds
participant "<<middleware>>\n:auth" as middlewareAuth
participant "<<controllers>>\n:campgrounds" as controllersCampgrounds
participant "<<models>>\n:Campground" as modelCampground
participant "<<models>>\n:Booking" as modelBooking
participant "<<models>>\n:Review" as modelReview
participant "<<models>>\n:Promotion" as modelPromotion
database "<<MongoDB>>\n:campgrounds" as CampgroundsDatabase


routerCampgrounds -> middlewareAuth ++: protect(),authorize('admin')
middlewareAuth -> controllersCampgrounds ++: updateCampground()
controllersCampgrounds -> modelCampground ++: findByIdAndUpdate(req.params.id, req.body)
modelCampground -> CampgroundsDatabase ++: CampgroundSchema
CampgroundsDatabase --> modelCampground --: Campground
controllersCampgrounds->client --: response (Updated Campground)


@enduml
