@startuml manage-bookings

header Booking Management Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Bookings(Add Booking )"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<routes>>\n:bookings" as routerBookings
participant "<<middleware>>\n:auth" as middlewareAuth
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<models>>\n:Booking" as modelBooking
participant "<<models>>\n:Campground" as modelCampground
database "<<MongoDB>>\n:bookings" as BookingsDatabase


routerBookings -> middlewareAuth ++: protect(), authorize('admin','user')
middlewareAuth -> controllersBookings ++: addBooking()
controllersBookings -> modelCampground ++: findById(req.params.campgroundId)
modelCampground -> BookingsDatabase ++: CampgroundSchema
BookingsDatabase --> modelCampground --: Campground
controllersBookings -> modelBooking ++: create(req.body)
modelBooking -> BookingsDatabase ++: BookingSchema
controllersBookings->client --: response (New Booking Created)
